import type { SparePart } from '../spare-parts/entities/spare-part.entity';

const SEED_TIMESTAMP = new Date('2026-04-27T00:00:00.000Z');

/**
 * Spare-part roster (~20 entries spanning all six categories).
 * Includes the workshop's flagship wink: P-FLUX-CAP-MK2 priced at
 * €88,888.88, compatible only with V008 (the DeLorean DMC-12).
 * Step 05 (Exception Filters) hangs the MissingFluxCapacitorException
 * teaching moment off this part.
 */
export const SPARE_PARTS_SEED: ReadonlyArray<SparePart> = [
  // engine
  {
    id: 'P001',
    partNumber: 'OIL-FLT-001',
    name: 'Oil filter',
    category: 'engine',
    priceEur: 12.5,
    stock: 80,
    compatibleVehicleIds: ['V001', 'V002', 'V004', 'V006'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P002',
    partNumber: 'AIR-FLT-002',
    name: 'Air filter',
    category: 'engine',
    priceEur: 18.9,
    stock: 60,
    compatibleVehicleIds: ['V001', 'V002', 'V003', 'V004', 'V006', 'V012'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P003',
    partNumber: 'SPK-PLG-003',
    name: 'Spark plug set',
    category: 'engine',
    priceEur: 32.0,
    stock: 45,
    compatibleVehicleIds: ['V001', 'V002', 'V004', 'V005', 'V006'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P004',
    partNumber: 'TRB-CRT-004',
    name: 'Turbo cartridge',
    category: 'engine',
    priceEur: 480.0,
    stock: 4,
    compatibleVehicleIds: ['V006'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P005',
    partNumber: 'LMD-SNS-005',
    name: 'Lambda sensor',
    category: 'engine',
    priceEur: 95.0,
    stock: 22,
    compatibleVehicleIds: ['V001', 'V002', 'V003', 'V004', 'V012'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  // brakes
  {
    id: 'P006',
    partNumber: 'BRK-PAD-006',
    name: 'Brake pads (front)',
    category: 'brakes',
    priceEur: 42.0,
    stock: 60,
    compatibleVehicleIds: ['V001', 'V002', 'V004', 'V006', 'V007', 'V012'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P007',
    partNumber: 'BRK-RTR-007',
    name: 'Brake rotor',
    category: 'brakes',
    priceEur: 78.0,
    stock: 35,
    compatibleVehicleIds: ['V001', 'V002', 'V006', 'V007', 'V011'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P008',
    partNumber: 'BRK-FLD-008',
    name: 'Brake fluid (1L)',
    category: 'brakes',
    priceEur: 9.5,
    stock: 100,
    compatibleVehicleIds: ['V001', 'V002', 'V003', 'V004', 'V005', 'V006', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  // tires
  {
    id: 'P009',
    partNumber: 'TRE-205-009',
    name: 'Tire 205/55 R16',
    category: 'tires',
    priceEur: 110.0,
    stock: 24,
    compatibleVehicleIds: ['V001', 'V002', 'V004', 'V012'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P010',
    partNumber: 'TRE-225-010',
    name: 'Tire 225/40 R18',
    category: 'tires',
    priceEur: 165.0,
    stock: 16,
    compatibleVehicleIds: ['V006', 'V007', 'V011'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P011',
    partNumber: 'TRE-OFF-011',
    name: 'All-terrain tire (Hilux)',
    category: 'tires',
    priceEur: 195.0,
    stock: 12,
    compatibleVehicleIds: ['V003'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  // electrical
  {
    id: 'P012',
    partNumber: 'ALT-12V-012',
    name: '12V alternator',
    category: 'electrical',
    priceEur: 220.0,
    stock: 15,
    compatibleVehicleIds: ['V001', 'V002', 'V003', 'V004', 'V005', 'V006', 'V008'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P013',
    partNumber: 'BAT-LI-013',
    name: 'Li-ion EV battery cell',
    category: 'electrical',
    priceEur: 1200.0,
    stock: 6,
    compatibleVehicleIds: ['V007', 'V011'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P014',
    partNumber: 'HDL-LED-014',
    name: 'LED headlight',
    category: 'electrical',
    priceEur: 88.0,
    stock: 30,
    compatibleVehicleIds: ['V001', 'V002', 'V004', 'V007', 'V011', 'V012'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  // body
  {
    id: 'P015',
    partNumber: 'WND-FRT-015',
    name: 'Front windshield',
    category: 'body',
    priceEur: 320.0,
    stock: 8,
    compatibleVehicleIds: ['V001', 'V002', 'V004', 'V006', 'V012'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P016',
    partNumber: 'BUM-RR-016',
    name: 'Rear bumper',
    category: 'body',
    priceEur: 180.0,
    stock: 14,
    compatibleVehicleIds: ['V001', 'V004', 'V005'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  // misc
  {
    id: 'P017',
    partNumber: 'WPR-BLD-017',
    name: 'Wiper blade pair',
    category: 'misc',
    priceEur: 15.0,
    stock: 200,
    compatibleVehicleIds: ['V001', 'V002', 'V003', 'V004', 'V005', 'V006', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P018',
    partNumber: 'AC-CMP-018',
    name: 'A/C compressor',
    category: 'misc',
    priceEur: 290.0,
    stock: 9,
    compatibleVehicleIds: ['V002', 'V004', 'V006', 'V012'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'P019',
    partNumber: 'EXH-SLN-019',
    name: 'Exhaust silencer',
    category: 'misc',
    priceEur: 140.0,
    stock: 18,
    compatibleVehicleIds: ['V001', 'V002', 'V003', 'V004', 'V005', 'V010'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  // The wink — only compatible with the DeLorean (V008).
  {
    id: 'P020',
    partNumber: 'FLUX-CAP-MK2',
    name: 'Flux capacitor (Mk II)',
    category: 'electrical',
    priceEur: 88_888.88,
    stock: 1,
    compatibleVehicleIds: ['V009'],
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];
